dataset: "ESD-Chinese-Singing-MFA"

path:
  corpus_path: "./raw_data/ESD-Chinese-Singing-MFA"
  sub_dir_name: ""
  lexicon_path: "./lexicon/esd-chinese-singing-mfa-lexicon.txt"
  raw_path: "./raw_data/ESD-Chinese-Singing-MFA"
  preprocessed_path: "./preprocessed_data/ESD-Chinese-Singing-MFA"
  
preprocessing:
  val_size: 512
  text:
    text_cleaners: ["basic_cleaners"]
    language: "zh"
    
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
    
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
    
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000
    
  pitch:
    feature: "phoneme_level"
    normalization: True
    
  energy:
    feature: "phoneme_level"
    normalization: True 